//
//  SearchMoviesModels.swift
//  Popcorn
//
//  Created by Hashem Aboonajmi on 3/29/18.
//  Copyright (c) 2018 Hashem Aboonajmi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import Foundation

enum SearchMovies
{
    enum Section: Int {
        case movies
        case activityIndicator
    }
    
    // MARK: Use cases
    
    enum Search
    {
        struct Request
        {
            let searchTerm: String
        }
        struct Response
        {
            let movies: [Movie]
        }
        struct ViewModel
        {
            // We seperate display model from domain model, by defining a view model
            struct DisplayMovie {
                let id: Int
                let title: String
                let posterURL: URL?
                let releaseDate: String
                let description: String
            }
            
            let displayedMovies: [DisplayMovie]
        }
    }
    
    enum SearchFailure
    {
        struct Response {
            let error: Error
        }
        
        struct ViewModel {
            enum Reason {
                case noConnection, error(message: String)
            }
            let reason: Reason
        }
    }
    
    enum FetchRecentSearches {
        
        struct Response {
            let recentSearches: [String]
        }
        
        struct ViewModel {
            let recentSearches: [String]
        }
    }
}

