//
//  SearchMoviesInteractor.swift
//  Popcorn
//
//  Created by Hashem Aboonajmi on 3/29/18.
//  Copyright (c) 2018 Hashem Aboonajmi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol SearchMoviesBusinessLogic
{
    
}

protocol SearchMoviesDataStore
{
    
}

class SearchMoviesInteractor: SearchMoviesBusinessLogic, SearchMoviesDataStore
{
    var presenter: SearchMoviesPresentationLogic?
    var worker: SearchMoviesWorker?
    
    
}

